'''
String template used for the GMock mock file output

{0} = Base Class Namespace
{1} = Generated mock classes
'''
GMOCK_FILE_TEMPLATE = \
'''/** @file
    GENERATED by CFunctionWrapperGenerator
    DO NOT MODIFY
*/

#pragma once

#ifndef {0}_MOCK_CWRAPPERS_H
#define {0}_MOCK_CWRAPPERS_H

#include <gmock/gmock.h>
#include <{0}/ICWrappers.h>

{1}

#endif

'''

'''
String template used for the Component file output

{0} = Base Class Namespace
{1} = Necessary headers (include real C function prototypes)
{2} = Component Classes
{3} = Namespace hierarchy with class declarations
'''
COMPONENT_FILE_TEMPLATE = \
'''/** @file
    GENERATED by CFunctionWrapperGenerator
    DO NOT MODIFY
*/

#pragma once

#ifndef {0}_COMPONENT_CWRAPPERS_H
#define {0}_COMPONENT_CWRAPPERS_H

{1}
#include <{0}/ICWrappers.h>

{3}
{2}

#endif

'''

'''
String template used for the interface file

{0} = Base Class Namespace
{1} = Interface Class Defintions
{2} = List of class declarations (e.g. class ISomething;)
{3} = List of include directives
'''
INTERFACE_FILE_TEMPLATE = \
'''/** @file
    GENERATED by CFunctionWrapperGenerator
    DO NOT MODIFY
*/

#pragma once

#ifndef {0}_ICWRAPPERS_H
#define {0}_ICWRAPPERS_H

{3}

namespace {0}
{{
    {2}
}}

{1}

#endif

'''

'''
String template used for generating individual classes
which implement an interface

{0} = Fully qualified class name
{1} = List of fully qualified inherited class names
{2} = Functions
{3} = Class Name
'''
INHERITING_CLASS_TEMPLATE = \
'''class {0} : public {1}
{{
public:
    virtual ~{3}() {{}}

    {2}
}};

'''

'''
String template used for generating individual
interface classes

{0} = Fully qualified interface name
{1} = Functions
{2} = Class Name
'''
INTERFACE_CLASS_TEMPLATE = \
'''class {0}
{{
public:
    virtual ~{2}() {{}}

    {1}
}};

'''

'''
String template used for generating individual
interface function prototypes

{0} = Return Type
{1} = Wrapper function prefix
{2} = Wrapped function name
{3} = Function Argument type and names list
{4} = Function Qualifier (optional)
'''
INTERFACE_FUNCTION_TEMPLATE = 'virtual {0} {1}{2} ({3}) {4} = 0;'

'''
String template used for generating individual wrapper
function implementations

{0} = Return type
{1} = Wrapper function prefix
{2} = Wrapped function name
{3} = Function Argument type and names list
{4} = Function Qualifier (optional)
{5} = Function Argument names list
'''
COMPONENT_FUNCTION_TEMPLATE = \
'''{0}
    {1}{2} ({3}) {4}
    {{
        return {2}({5});
    }}

'''

'''
{0} = GMock MOCK_METHOD* or MOCK_CONST_METHOD* name
{1} = Mocked function name
{2} = Return type
{3} = Function argument type and names list
'''
GMOCK_DECLARATION_TEMPLATE = '{0}({1}, {2}({3}));'